---
- name: CentOS | Install Certbot
  yum:
    name: "certbot"
    state: "latest"
  when: "'pterodaemon' in group_names"

- name: CentOS | Install Certbot-nginx
  yum:
    name: "python2-certbot-nginx"
    state: "latest"
  when: "'pteropanel' in group_names"

- name: CentOS | Get service List
  service_facts:

- name: CentOS | Check for Nginx
  set_fact:
    is_nginx: true
  when: services["nginx"] is defined

- name: CentOS | Check for Apache
  set_fact:
    is_apache: true
  when: services["apache2"] is defined

- name: CentOS | Stop Nginx
  service: name=nginx state=stopped
  when: is_nginx is defined

- name: CentOS | Stop Apache
  service: name=apache2 state=stopped
  when: is_apache is defined

- name: CentOS | Generate Certbot Certificate STAGING
  command: certbot certonly --standalone -m {{ letsencrypt_email }} --agree-tos -d {{ domain_name }} --staging
  args:
    creates: "/etc/letsencrypt/live/{{ domain_name }}/fullchain.pem"
  when: staging

- name: CentOS | Generate Certbot Certificate PRODUCTION
  command: certbot certonly --standalone -m {{ letsencrypt_email }} --agree-tos -d {{ domain_name }}
  args:
    creates: "/etc/letsencrypt/live/{{ domain_name }}/fullchain.pem"
  when: staging is defined and staging is match("false")

- name: CentOS | Start Nginx
  service: name=nginx state=started
  when: is_nginx is defined

- name: CentOS | Start Apache
  service: name=apache2 state=started
  when: is_apache is defined
...